# Generated by Django 3.2.9 on 2021-11-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.CharField(max_length=200, null=True)),
                ('Usuario', models.CharField(max_length=200)),
                ('fecPrestamo', models.DateTimeField()),
                ('feacDevolucion', models.DateTimeField(null=True)),
            ],
        ),
    ]
