# Generated by Django 3.2.6 on 2021-09-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('dni', models.IntegerField(default=0)),
                ('telefono', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=200)),
                ('fecha_de_nacimiento', models.DateTimeField()),
                ('fecha_de_publicacion', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
